final List<String> loadingTexts = [
  "Calibrating Morty neurons…",
  "Activating synapses…",
  "Charging brain cells…",
  "Loading neural goo…",
  "Splicing cognitive pathways…",
  "Aligning brain waves…",
  "Summoning awful creatures…",
  "Injecting chaos…",
  "Warping reality…",
  "Preparing multiverse mayhem…",
  "Brain juice flowing…",
  "Loading horrors…",
  "Gearing up chaos…",
  "Training Morty AI with bad jokes…",
  "Generating fake randomness...",
  "Charging portal gun battery...",
  "Installing extra bugs…",
  "Encrypting useless data...",
  "Faking the game load…",
  "Loading hardest examples…",
  "Preparing intergalactic war…",
];
